### ISSUE TITLE
Effect size information

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/many_analyses#14]
- https://www.reddit.com/r/statistics/comments/fouwp9/q_effect_size_calculation_for_brms_delta_t/
- https://www.barelysignificant.com/phd_thesis/appendix-brms.html#inference-and-conclusions
- https://www.researchgate.net/publication/250185702_Effect_Sizes_in_Cluster-Randomized_Designs

**Comment by troettge** [comment]
I pushed a script sim_raw.R with simple scenarios of how models could look like. I don't have time for much more detailed thinking, but maybe you guys could have a look and think about this issue. Big question: How do we extract the ES from these models? @jvcasillas @stefanocoretta

**Comment by stefanocoretta** [comment]
Thanks for working on that! It's awesome! 

You might have discussed this already, but I wonder whether pooling effect sizes from models that might have different outcome variables is a viable step (even considering that the ESs are standardised). What if we just code a binary variable yes/no depending of whether the team argues to have found an effect or not? And for the ESs/model specifications we do a more descriptive analysis? This would spare us from the complexities of calculating unified ESs considering the variety of possible outcome variables, models, and models specifications.

**Comment by troettge** [comment]
Mhm, great suggestion. But don't we actually want to quantify the quantitative estimates rather than the probability of dichotomous decisions? I totally see the appeal of the latter and that might actually be very interesting in terms of the covariates (e.g. does say analysis quality increase the P of finding an effect. Maybe both. Keep in mind, that with regard to the dichotomous decisions we might get a floor effect (nobody actually claims an effect).

**Comment by troettge** [comment]
One thing I came across, I don't think it would be legit to recode peoples predictors, because that might actually lead to a different interpretation (people might interpret a dummy-coded interaction term as significant, while a deviation-coded version, does not show such a significant effect). Currently working on RR
