### ISSUE TITLE
Audio files (long vs. segmented)

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/many_analyses#23]
Pros and cons

**Comment by stefanocoretta** [comment]
My preference would be:

- One `.wav` and `.TextGrid` per speaker.
- (Automatic) Force-aligned segmentation of sentences, words, segments.

I think having a single file per speaker is easier to manage than one per utterance, and if people wanna split them into separate files they can use the sentence tier in the segmentation to do so. Having a force-aligned segmentation would also be beneficial to the teams, since they won't have to know German and could just look at the segmentation instead (with the caveat that the segmentation is not corrected, so there might be mistakes).

**Comment by stefanocoretta** [comment]
We're gonna go with one file per speaker.
