### ISSUE TITLE
Analytical approach collection questionnaire

### ISSUE THREAD

**Issue by stefanocoretta** [jvcasillas/many_analyses#8]
Points to discuss on the questionnaire for the collection of the analytical approach:

1. S et al have included a box for pasting a script (if any). Do we want that or do we want to collect scripts differently?
2. S et al have a question about their research questions and ask how likely the teams think that soccer referees tend to give more red cards to dark skinned players (and there's a Likert scale from very unlikely to very likely)? How could our question about prosodic variation be formulated?

**Comment by troettge** [comment]
1. The script question somewhat hinges on software, e.g. if you use SPSS, you don't necessarily have a script (I think you can generate one from your click-analysis tho). I would suggest we follow [the many ecologist path](https://osf.io/neyc7/) and simply ask them to (a) write up their methods as if they would submit it to a journal and ask specific questions about important aspects of the analysis. If they want (and we encourage that), they can upload scripts.

2. Yes, we should definitely ask them about their priors. But in order not to bias them, we need to carefully think about how to frame the research question in our project description. The way it is written atm, strikes me as biased toward an effect. An analog question would be: 

"Do speakers modify the speech signal to indicate the typicality of a modifier - noun combination, i.e. does the prosodic profile of blue banana (atypical) differ from that of yellow banana (typical)"

**Comment by stefanocoretta** [comment]
Notes for later discussion:

- Q SM06 var-oper: example with categorical variables.

**Comment by stefanocoretta** [comment]
The latest version of the form can be found [here](https://github.com/jvcasillas/many_analyses/blob/master/docs/questionnaires/analytic.pdf).

**Comment by troettge** [comment]
Some comments from my side: 

Question 6: I have rewritten the example a little bit. See if you find it useful. E.g. I find it a little less ambigiuous to speak of domains rather than units.

"For example, if you choose f0 as a variable, specify from which speech domain it was extracted (for example: the phrase, the word, the syllable, the vowel, etc.), whether you extracted a summary statistic over a larger domain or a concrete value at a specific or relative point in time. For categorical variables (like age, gender, etc.), specify the levels/categories, how they are operationalised and the rationale behind the categorisation."

10. Delete “Remember that this result will not be shared with other teams at this stage." as we do not plan to give them this discussion round right? 

Additional questions that aim at revising earlier decision that we might want to know more about: 

When did you decide on what to measure and how to operationalize the acoustic measures to ultimately answer the research question?

- Before I looked at the acoustic data
- After I looked at some of the data, but before I extracted the acoustic data 
- After I extracted the acoustic data, but before I performed statistical analyses
- After I have performed some statistical analyses

When did you decide on how to statistically answer the research question?

- Before I looked at the acoustic data
- After I looked at some of the data, but before I extracted the acoustic data 
- After I extracted the acoustic data, but before I performed statistical analyses
- After I have performed some statistical analyses

--> Could be multiple choice, or open question.

Often we do not anticipate possible road blocks during our analyses. Did you encounter scenarios in which you had to revise an earlier analytical decision at a later stage, e.g. change a measurement  after you have statistically analyzed (parts of) the data? If so, please briefly describe the situation.

In your final report, did you report on all acoustic parameters that you have extracted from the speech recordings?

Did you preregister any steps of your analysis? (A preregistration is a timestamped document that details all relevant methodological steps before the analysis.)

What do you think?

**Comment by jvcasillas** [comment]
I agree with most of what @troettge mentions. 

> Some comments from my side:
> 
> Question 6: I have rewritten the example a little bit. See if you find it useful. E.g. I find it a little less ambigiuous to speak of domains rather than units.
> 
> "For example, if you choose f0 as a variable, specify from which speech domain it was extracted (for example: the phrase, the word, the syllable, the vowel, etc.), whether you extracted a summary statistic over a larger domain or a concrete value at a specific or relative point in time. For categorical variables (like age, gender, etc.), specify the levels/categories, how they are operationalised and the rationale behind the categorisation."
> 

Seems good. Also, should be "operationalize" (without the "d"). 

> 1. Delete “Remember that this result will not be shared with other teams at this stage." as we do not plan to give them this discussion round right?
> 

This was my understanding too. 

> Additional questions that aim at revising earlier decision that we might want to know more about:
> 
> When did you decide on what to measure and how to operationalize the acoustic measures to ultimately answer the research question?
> 
> * Before I looked at the acoustic data
> * After I looked at some of the data, but before I extracted the acoustic data
> * After I extracted the acoustic data, but before I performed statistical analyses
> * After I have performed some statistical analyses
> 
> When did you decide on how to statistically answer the research question?
> 
> * Before I looked at the acoustic data
> * After I looked at some of the data, but before I extracted the acoustic data
> * After I extracted the acoustic data, but before I performed statistical analyses
> * After I have performed some statistical analyses
> 
> --> Could be multiple choice, or open question.
> 

These seem like reasonable questions. Depending on their knowledge of p-hacking and open science/reproducibility more generally, they might not want to answer these questions. Should we add some kind reassurance that we don't really care what they did?


> Often we do not anticipate possible road blocks during our analyses. Did you encounter scenarios in which you had to revise an earlier analytical decision at a later stage, e.g. change a measurement after you have statistically analyzed (parts of) the data? If so, please briefly describe the situation.
> 

I like this too. 

> In your final report, did you report on all acoustic parameters that you have extracted from the speech recordings?
> 
> Did your final report reflect all analytical decision that you have explored. E.g. if your final report describes a main effect of a predictor, did you also run a model with an interaction term? if your final report describes statistical models with one or more dependent variables, did you test any other dependent variables? if your final report describes a particular statistical model or test, did you try any other models or tests? If any of these scenarios is true, what did you do and why did you not include it in the final report?
> 
> Did you preregister any steps of your analysis? (A preregistration is a timestamped document that details all relevant methodological steps before the analysis.)
> 
> What do you guys think?

These all seem like good additions, but I do worry about making this too long. I imagine that the longer the questionnaire is the shorter their responses will be. Something to think about.

**Comment by stefanocoretta** [comment]
This commit 634f96d addresses some of the revisions above. It would be nice to include also the three last questions, but I agree that keeping the questionnaire shorter would be good. Let's think about this.

**Comment by jvcasillas** [comment]
Ported to google forms: 

- intake form: https://forms.gle/aNYnWa5bULy6rxtb7
- analytical form: https://forms.gle/JVsZypf6Adp8Ygmx8
